// Generated by CoffeeScript 1.6.3
(function() {
  var scrollable;

  scrollable = function(opts) {
    var animate, currentVal, defaults, index, operateDom, pDim, pSize, result, setting, targetVal;
    defaults = {
      vertical: false
    };
    setting = {};
    result = {};
    (function() {
      var item, x;
      for (x in defaults) {
        item = defaults[x];
        setting[x] = item;
      }
    })();
    (function() {
      var item, x;
      for (x in opts) {
        item = opts[x];
        setting[x] = item;
      }
    })();
    if (setting.vertical) {
      pDim = 'top';
      pSize = setting.container.offsetHeight;
    } else {
      pDim = 'left';
      pSize = setting.container.offsetWidth;
    }
    operateDom = setting.container.children[0];
    animate = new Animate();
    index = 0;
    currentVal = 0;
    targetVal = 0;
    animate.step = function(progress) {
      var distance;
      distance = targetVal - currentVal;
      operateDom.style[pDim] = -(currentVal + distance * progress) + 'px';
    };
    animate.complete = function() {
      currentVal = targetVal;
    };
    result.seekTo = function(i) {
      animate.stop();
      targetVal = i * pSize;
      animate.start();
      index = i;
      if (setting.onSeek) {
        setting.onSeek();
      }
    };
    result.onSeek = function(fun) {
      setting.onSeek = fun;
    };
    result.getIndex = function() {
      return index;
    };
    return result;
  };

  window.scrollable = scrollable;

}).call(this);
